name: JSON Lint Check

on:
  push:
    branches:
      - "**"   # Run on all branches

jobs:
  jsonlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate all JSON files
        run: |
          npm install -g jsonlint

          FILES=$(find . -name "*.json")

          if [ -z "$FILES" ]; then
            echo "No JSON files found, skipping."
            exit 0
          fi

          for file in $FILES; do
            echo "Checking $file..."
            jsonlint "$file" || { echo "❌ Invalid JSON in $file"; exit 1; }
          done
